import type { IndustryPack } from './index'

export const constructionPack: IndustryPack = {
  id: 'construction',
  label: 'Строительство',
  description: 'Управление капитальным строительством — 4D BIM, контроль СМР, план/факт',
  assetHierarchy: [
    'Холдинг / Застройщик',
    'Проект / Объект',
    'Очередь / Секция',
    'Захватка / Элемент',
  ],
  kpis: [
    { id: 'physical_progress',   label: 'Физический прогресс',            unit: '%'         },
    { id: 'earned_value_pct',    label: 'Освоение бюджета (EV)',          unit: '%'         },
    { id: 'spi',                 label: 'SPI (индекс выполнения сроков)', unit: '—'         },
    { id: 'cpi',                 label: 'CPI (индекс выполнения затрат)', unit: '—'         },
    { id: 'schedule_variance',   label: 'Отклонение от графика',          unit: 'дн.'       },
    { id: 'lagging_zones',       label: 'Отставание захваток',            unit: 'шт.'       },
    { id: 'daily_smr_value',     label: 'Выполнение СМР',                 unit: 'млн ₸/сут' },
    { id: 'materials_coverage',  label: 'Обеспеченность материалами',     unit: '%'         },
    { id: 'quality_deviations',  label: 'Отклонения качества',            unit: 'шт.'       },
    { id: 'safety_ltifr',        label: 'Охрана труда (LTIFR)',           unit: 'на 1М ч.'  },
  ],
  modules: [
    { id: 'dashboard',      label: 'Главная',                  icon: 'LayoutDashboard', route: '/'                          },
    { id: '4d_model',       label: '4D-модель',                icon: 'Box',             route: '/construction-4d'           },
    { id: 'planning',       label: 'График и планирование',    icon: 'CalendarRange',   route: '/construction-planning'     },
    { id: 'budget',         label: 'Смета и бюджет',           icon: 'FileBarChart2',   route: '/construction-budget'       },
    { id: 'progress',       label: 'Контроль СМР (план/факт)', icon: 'Gauge',           route: '/construction-progress'     },
    { id: 'crews',          label: 'Бригадиры',                icon: 'HardHat',         route: '/construction-crews'        },
    { id: 'journal',        label: 'Суточный журнал',          icon: 'ClipboardList',   route: '/construction-journal'      },
    { id: 'cv_monitoring',  label: 'CV-мониторинг (дрон)',     icon: 'ScanEye',         route: '/construction-cv'           },
    { id: 'digital_twin',   label: 'Цифровой двойник стройки', icon: 'Workflow',        route: '/construction-digital-twin' },
    { id: 'integrations',   label: 'Интеграции',               icon: 'Plug',            route: '/integrations'              },
  ],
  integrations: [
    'Autodesk BIM 360 / ACC',
    'Autodesk Navisworks',
    'Oracle Primavera P6',
    'Microsoft Project',
    '1С:ERP',
    '1С:УПП',
    '1С:Бухгалтерия',
    'SAP PS',
    'Trimble Tekla Structures',
    'СОД / CDE (общая среда данных)',
  ],
}
